import "./globals.css";
import { Navbar5 } from "@/components/navbar-05";
import { Footer9 } from "@/components/footer-09";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Navbar5 />
        {children}
        <Footer9 />
      </body>
    </html>
  );
}
