export const TITLE = "Terms of Use";
export const UPDATED = "February 11, 2026";

export const CONTENT = [
  { type: "h", text: "Agreement to Terms" },
  { type: "p", text: "Welcome to Uplift Path, Inc. (\"Uplift Path,\" \"we,\" \"us,\" or \"our\"). These Terms of Use (\"Terms\") govern your access to and use of our website located at upliftpathwellness.com (the \"Website\"), including all content, features, and services offered on or through the Website." },
  { type: "p", text: "PLEASE READ THESE TERMS CAREFULLY BEFORE USING OUR WEBSITE." },
  { type: "p", text: "By accessing or using the Website, you agree to be bound by these Terms and our Privacy Policy, incorporated herein by reference. If you do not agree to these Terms, you must not access or use the Website." },
  { type: "h", text: "Eligibility" },
  { type: "p", text: "You must be at least 18 years of age to use this Website. By using the Website and agreeing to these Terms, you represent and warrant that you are at least 18 years of age and have the legal capacity to enter into a binding agreement." },
  { type: "h", text: "Services Overview" },
  { type: "p", text: "Uplift Path currently provides Behavioral Health Consulting Services , including:" },
  {
    type: "ul",
    items: [
      "Strategic consulting and operational support for behavioral health organizations",
      "Business process optimization and compliance guidance",
      "Quality improvement program development",
      "Workforce development and training support",
      "Technology implementation and integration consulting",
    ],
  },
  { type: "h", text: "Future Clinical Services" },
  { type: "p", text: "Uplift Path has applied for CARF (Commission on Accreditation of Rehabilitation Facilities) accreditation to provide Community Psychiatric Supportive Treatment (CPST) services via telehealth for adults aged 18+ with active Medicaid coverage. These clinical services will be available only after:" },
  {
    type: "ul",
    items: [
      "CARF accreditation approval",
      "Ohio Mental Health and Addiction Services (OMHAS) licensure",
      "Medicaid provider enrollment completion",
      "Formal announcement on this Website",
    ],
  },
  { type: "p", text: "We are not currently accepting clients for CPST services. Information about future CPST services on the Website is for informational purposes only." },
  { type: "h", text: "Terms of Use" },
  { type: "h", text: "Permitted Use" },
  { type: "p", text: "You may access and use the Website for lawful purposes only, including:" },
  {
    type: "ul",
    items: [
      "Learning about Uplift Path's consulting services and future clinical services",
      "Submitting general inquiries about consulting services through contact forms",
      "Accessing publicly available resources and information",
      "Applying for employment or contractor opportunities",
    ],
  },
  { type: "p", text: "Prohibited Conduct You agree not to:" },
  { type: "p", text: "Violate Laws or Regulations: Use the Website in any manner that violates applicable federal, state, local, or international laws or regulations." },
  { type: "h", text: "Interfere with Website Operations:" },
  {
    type: "ul",
    items: [
      "Interfere with, disrupt, or attempt to gain unauthorized access to the Website or its servers.",
      "Use any robot, spider, scraper, or automated means to access the Website without our express written permission.",
      "Introduce viruses, malware, ransomware, or other malicious code.",
    ],
  },
  { type: "h", text: "Misuse Information:" },
  {
    type: "ul",
    items: [
      "Harvest, collect, or store personal information about other users.",
      "Use information obtained from the Website for unsolicited marketing or commercial purposes.",
      "Reproduce, modify, distribute, or create derivative works from Website Content without written permission.",
    ],
  },
  { type: "h", text: "Misrepresent Identity:" },
  {
    type: "ul",
    items: [
      "Impersonate any person or entity.",
      "Falsely state or misrepresent your affiliation with any person or entity.",
      "Provide false, inaccurate, or misleading information.",
    ],
  },
  { type: "h", text: "Post Inappropriate Content:" },
  { type: "p", text: "Post, transmit, or share content that is threatening, harassing, defamatory, obscene, fraudulent, or otherwise objectionable." },
  { type: "p", text: "Post content that infringes on intellectual property rights or violates privacy rights." },
  { type: "p", text: "Circumvent Security Measures: Attempt to bypass, disable, or interfere with security-related features of the Website." },
  { type: "h", text: "Registration and Account Security" },
  { type: "p", text: "If you create an account or register for services through the Website:" },
  {
    type: "ul",
    items: [
      "You must provide accurate, complete, and current information.",
      "You are responsible for maintaining the confidentiality of your username and password.",
      "You are responsible for all activities that occur under your account.",
      "You must notify us immediately of any unauthorized use of your account or any security breach.",
      "We reserve the right to suspend or terminate accounts that violate these Terms or for other legitimate reasons.",
    ],
  },
  { type: "h", text: "Intellectual Property Rights" },
  { type: "p", text: "\"Uplift Path\" our logo, and other marks used on the Website are trademarks or service marks of Uplift Path Inc. All other trademarks, service marks, and logos are the property of their respective owners." },
  { type: "h", text: "User Submissions and Feedback" },
  { type: "p", text: "Ownership The Website and all Content, including text, graphics, logos, images, videos, software, and other materials, are owned by Uplift Path Inc. or our licensors and are protected by U.S. and international copyright, trademark, patent, trade secret, and other intellectual property laws." },
  { type: "p", text: "Limited License Subject to your compliance with these Terms, we grant you a limited, non-exclusive, non-transferable, non-sublicensable, revocable license to access and use the Website for personal, non-commercial purposes only." },
  { type: "p", text: "Restrictions You may not:" },
  {
    type: "ul",
    items: [
      "Copy, reproduce, modify, adapt, translate, or create derivative works from Website Content without our express written permission.",
      "Remove, alter, or obscure any copyright, trademark, or other proprietary notices.",
      "Use our trademarks, logos, or service marks without prior written consent.",
      "Frame, mirror, or incorporate any portion of the Website into another website or product.",
    ],
  },
  { type: "h", text: "Trademark" },
  { type: "p", text: "\"Uplift Path,\" our logo, and other marks used on the Website are trademarks or service marks of Uplift Path Inc. All other trademarks, service marks, and logos are the property of their respective owners." },
  { type: "h", text: "User Submissions and Feedback" },
  { type: "p", text: "General Inquiries and Submissions When you submit inquiries, feedback, suggestions, or other information through the Website (collectively, \"Submissions\"), you grant Uplift Path a perpetual, irrevocable, worldwide, royalty-free, transferable license to use, reproduce, modify, distribute, and display such Submissions for any purpose without compensation or attribution to you." },
  { type: "p", text: "Future Clinical Services Once CPST clinical services are available and you submit a service request or intake form containing health information:" },
  {
    type: "ul",
    items: [
      "That information will become Protected Health Information (PHI) governed by HIPAA and our Notice of Privacy Practices.",
      "Such information will not be subject to the license described above for general Submissions.",
      "Our use and disclosure of PHI will be strictly governed by HIPAA regulations, state law, and our Privacy Policy.",
      "Please see our Privacy Policy for complete information about how we protect your information.",
    ],
  },
  { type: "h", text: "Third-Party Links and Content" },
  { type: "p", text: "The Website may contain links to third-party websites, resources, or services that are not owned or controlled by Uplift Path Inc." },
  { type: "p", text: "We do not endorse or assume responsibility for any third-party content, websites, or services. Your use of third-party websites is at your own risk and subject to the terms and conditions and privacy policies of those third parties. We are not liable for any harm or damages related to your use of third-party websites or services." },
  { type: "h", text: "Privacy and Data Protection" },
  { type: "p", text: "Your use of the Website is governed by our Privacy Policy, available at upliftpathwellness.com/privacy-policy ." },
  { type: "p", text: "By using the Website, you consent to the collection, use, and disclosure of your information as described in our Privacy Policy, including:" },
  {
    type: "ul",
    items: [
      "Cookies and tracking technologies",
      "Analytics and performance monitoring",
      "Data security measures",
      "Your privacy rights",
    ],
  },
  { type: "h", text: "SMS Marketing Terms" },
  { type: "p", text: "By opting in to receive SMS communications from Uplift Path Inc., you agree to receive recurring marketing text messages at the phone number provided regarding our behavioral health services. Consent to receive SMS messages is not a condition of receiving services. Message frequency may vary. Standard message and data rates may apply. You may opt out at any time by replying STOP. For assistance, reply HELP or contact us at info@upliftpathinc.com . Uplift Path Inc. is not liable for delays or failures in SMS delivery due to factors outside our control." },
  { type: "h", text: "Disclaimer of Warranties" },
  { type: "p", text: "TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, THE WEBSITE AND ALL CONTENT ARE PROVIDED ON AN \"AS IS\" AND \"AS AVAILABLE\" BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED." },
  { type: "p", text: "UPLIFT PATH DISCLAIMS ALL WARRANTIES, INCLUDING BUT NOT LIMITED TO:" },
  { type: "p", text: "Merchantability : That the Website is suitable for any particular purpose" },
  { type: "p", text: "Fitness for a Particular Purpose : That the Website will meet your specific needs" },
  { type: "p", text: "Non-Infringement : That use of the Website will not infringe third-party rights" },
  { type: "p", text: "Accuracy or Completeness : That Content is accurate, complete, current, or error-free" },
  { type: "p", text: "Uninterrupted Access : That the Website will be available, uninterrupted, secure, or free from errors, viruses, or other harmful components" },
  { type: "p", text: "We do not warrant that:" },
  { type: "p", text: "The Website will meet your requirements or expectations" },
  { type: "p", text: "Any errors or defects will be corrected" },
  { type: "p", text: "The Website or servers are free from viruses or harmful components" },
  { type: "p", text: "Information about future services will remain current or unchanged" },
  { type: "p", text: "Some jurisdictions do not allow the exclusion of certain warranties, so some of the above exclusions may not apply to you." },
  {
    type: "ul",
    items: [
      "Merchantability: That the Website is suitable for any particular purpose",
      "Fitness for a Particular Purpose: That the Website will meet your specific needs",
      "Non-Infringement: That use of the Website will not infringe third-party rights",
      "Accuracy or Completeness: That Content is accurate, complete, current, or error-free",
      "Uninterrupted Access: That the Website will be available, uninterrupted, secure, or free from errors, viruses, or other harmful components",
    ],
  },
  { type: "h", text: "We do not warrant that:" },
  {
    type: "ul",
    items: [
      "The Website will meet your requirements or expectations",
      "Any errors or defects will be corrected",
      "The Website or servers are free from viruses or harmful components",
      "Information about future services will remain current or unchanged",
      "Some jurisdictions do not allow the exclusion of certain warranties, so some of the above exclusions may not apply to you.",
    ],
  },
  { type: "h", text: "Limitation of Liability" },
  { type: "p", text: "TO THE FULLEST EXTENT PERMITTED BY LAW, UPLIFT PATH, INC., ITS AFFILIATES, BOARD OF STRATEGIC ADVISORS, OFFICERS, EMPLOYEES, CONTRACTORS, AND AGENTS (COLLECTIVELY, \"UPLIFT PATH PARTIES\") SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, EXEMPLARY, OR PUNITIVE DAMAGES ARISING OUT OF OR RELATED TO:" },
  {
    type: "ul",
    items: [
      "Your use of or inability to use the Website",
      "Any Content or information obtained through the Website",
      "Unauthorized access to or alteration of your data or transmissions",
      "Any conduct or content of third parties on the Website",
      "Any third-party links, websites, or services",
      "Any interruption, error, or technical malfunction",
      "Any reliance on information about future services",
    ],
  },
  { type: "p", text: "THIS LIMITATION APPLIES WHETHER THE DAMAGES ARE BASED ON CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, WARRANTY, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT UPLIFT PATH HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES." },
  { type: "p", text: "MAXIMUM LIABILITY: In no event shall the total aggregate liability of Uplift Path Parties exceed the greater of (a) the amount you paid to Uplift Path in the six (6) months preceding the claim, if any, or (b) One Hundred Dollars ($100.00)." },
  { type: "p", text: "Some jurisdictions do not allow the limitation or exclusion of liability for incidental or consequential damages, so some of the above limitations may not apply to you." },
  { type: "h", text: "Indemnification" },
  { type: "p", text: "You agree to defend, indemnify, and hold harmless Uplift Path Parties from and against any and all claims, liabilities, damages, losses, costs, and expenses (including reasonable attorneys' fees) arising out of or related to:" },
  {
    type: "ul",
    items: [
      "Your use of or inability to use the Website",
      "Your violation of these Terms",
      "Your violation of any rights of another person or entity",
      "Your violation of any applicable law or regulation",
      "Any information or content you submit, post, or transmit through the Website",
    ],
  },
  { type: "p", text: "We reserve the right to assume the exclusive defense and control of any matter subject to indemnification, and you agree to cooperate with our defense of such claims." },
  { type: "h", text: "Modifications to the Website and Terms" },
  { type: "h", text: "Website Modifications" },
  { type: "p", text: "We reserve the right to:" },
  {
    type: "ul",
    items: [
      "Modify, suspend, or discontinue the Website (or any portion thereof) at any time without notice or liability.",
      "Change features, functionality, or Content.",
      "Impose limits on certain features or restrict access to parts or all of the Website.",
      "Update information about services, including future clinical services, as our accreditation and licensing status changes.",
      "Any information or content you submit, post, or transmit through the Website",
    ],
  },
  { type: "h", text: "Terms Modifications" },
  { type: "p", text: "We may update or revise these Terms from time to time. When we make material changes, we will:" },
  {
    type: "ul",
    items: [
      "Update the \"Last Updated\" date at the top of this page.",
      "Post the revised Terms on the Website.",
      "Provide notice as required by applicable law (e.g., via email or prominent Website notice).",
    ],
  },
  { type: "p", text: "Your continued use of the Website after changes are posted constitutes your acceptance of the revised Terms. If you do not agree to the revised Terms, you must stop using the Website immediately." },
  { type: "h", text: "Termination" },
  { type: "h", text: "Termination by You" },
  { type: "p", text: "You may stop using the Website at any time. If you have an account, you may request account deletion by contacting us at info@upliftpathinc.com ." },
  { type: "h", text: "Termination by Us" },
  { type: "p", text: "We reserve the right to suspend or terminate your access to the Website immediately, without prior notice or liability, for any reason, including but not limited to:" },
  {
    type: "ul",
    items: [
      "Violation of these Terms",
      "Fraudulent, abusive, or illegal activity",
      "Behavior that harms Uplift Path, other users, or third parties",
      "Any other reason at our sole discretion",
    ],
  },
  { type: "h", text: "Upon termination:" },
  {
    type: "ul",
    items: [
      "Your right to use the Website immediately ceases.",
      "We may delete your account and any associated data.",
      "Provisions of these Terms that by their nature should survive termination will remain in effect.",
    ],
  },
  { type: "h", text: "Governing Law and Jurisdiction" },
  { type: "p", text: "These Terms shall be governed by and construed in accordance with the laws of the State of Delaware, without regard to its conflict of law principles." },
  { type: "p", text: "You agree that any legal action or proceeding arising out of or related to these Terms or your use of the Website shall be brought exclusively in the state or federal courts located in Franklin County, Ohio, and you consent to the personal jurisdiction of such courts." },
  { type: "h", text: "Dispute Resolution and Arbitration" },
  { type: "h", text: "Informal Resolution" },
  { type: "p", text: "Before initiating any formal dispute resolution, you agree to contact us at info@upliftpathinc.com to attempt to resolve the dispute informally. We will attempt to resolve disputes in good faith." },
  { type: "h", text: "Binding Arbitration" },
  { type: "h", text: "Exceptions to Arbitration" },
  { type: "p", text: "Notwithstanding the above, either party may seek injunctive or equitable relief in court to prevent infringement of intellectual property rights or confidential information." },
  { type: "h", text: "Class Action Waiver" },
  { type: "p", text: "YOU AGREE THAT ANY ARBITRATION OR PROCEEDING SHALL BE LIMITED TO THE DISPUTE BETWEEN YOU AND UPLIFT PATH INDIVIDUALLY. TO THE FULLEST EXTENT PERMITTED BY LAW, YOU WAIVE ANY RIGHT TO PARTICIPATE IN A CLASS ACTION LAWSUIT OR CLASS-WIDE ARBITRATION." },
  { type: "h", text: "Accessibility" },
  { type: "p", text: "Uplift Path is committed to ensuring digital accessibility for all users, including individuals with disabilities. We strive to meet Web Content Accessibility Guidelines (WCAG) 2.1 Level AA standards." },
  { type: "p", text: "If you experience difficulty accessing any part of the Website or need materials in an alternative format, please contact our Chief Risk Officer at privacy@upliftpathinc.com or 513-299-4553.For more information, see our Accessibility Statement." },
  { type: "h", text: "Export Controls and Compliance" },
  { type: "p", text: "You represent and warrant that you are not located in, or a resident or national of, any country subject to U.S. government embargo or designated as a \"terrorist supporting\" country, and you are not on any U.S. government list of prohibited or restricted parties. You agree to comply with all applicable export control laws and regulations." },
  { type: "h", text: "Miscellaneous Provisions" },
  { type: "h", text: "Entire Agreement" },
  { type: "p", text: "These Terms, together with our Privacy Policy and any other policies referenced herein, constitute the entire agreement between you and Uplift Path regarding your use of the Website and supersede all prior agreements and understandings." },
  { type: "h", text: "Severability" },
  { type: "p", text: "If any provision of these Terms is found to be invalid, illegal, or unenforceable, the remaining provisions will continue in full force and effect." },
  { type: "h", text: "No Waiver" },
  { type: "p", text: "Our failure to enforce any right or provision of these Terms will not be deemed a waiver of such right or provision." },
  { type: "h", text: "Assignment" },
  { type: "p", text: "You may not assign or transfer your rights or obligations under these Terms without our prior written consent. We may assign or transfer our rights and obligations without restriction." },
  { type: "h", text: "Force Majeure" },
  { type: "p", text: "Uplift Path shall not be liable for any failure or delay in performance due to circumstances beyond our reasonable control, including but not limited to acts of God, natural disasters, war, terrorism, labor disputes, or government actions." },
  { type: "h", text: "Contact Information" },
  { type: "p", text: "If you have questions, concerns, or complaints regarding these Terms of Use, please contact us:" },
  { type: "p", text: "Uplift Path Inc." },
  { type: "p", text: "20 E Broad St, Suite 225" },
  { type: "p", text: "Columbus, OH 43215" },
  { type: "p", text: "United States" },
  { type: "p", text: "General Inquiries:" },
  { type: "p", text: "Email: info@upliftpathinc.com" },
  { type: "p", text: "Phone: 513-299-4553" },
  { type: "p", text: "Online Form: upliftpathwellness.com/contact" },
  { type: "p", text: "Privacy and Compliance Matters:" },
  { type: "p", text: "Email: privacy@upliftpathinc.com" },
  { type: "p", text: "Phone: 513-299-4553" },
  { type: "p", text: "Website: upliftpathwellness.com" },
  { type: "h", text: "Acknowledgment" },
  { type: "p", text: "BY USING THE WEBSITE, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE TERMS OF USE AND OUR PRIVACY POLICY." },
  { type: "p", text: "If you do not agree to these Terms, you must immediately cease using the Website." },
  { type: "p", text: "© 2026 Uplift Path, Inc. All Rights Reserved." },
];
